version: "3.1"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./www:/var/www/html
    depends_on:
      - wordpress
    networks:
      - internal
      - front
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.port: 80
      traefik.protocol: http
      traefik.frontend.rule: Host:website.com, www.website.com
      traefik.frontend.priority: 1
      traefik.docker.network: traefik_front
      traefik.frontend.redirect.regex: "^https?://www.website.com/(.*)"
      traefik.frontend.redirect.replacement: "https://website.com/$$1"
      traefik.frontend.redirect.permanent: true

  wordpress:
    build:
      context: .
    restart: unless-stopped
    volumes:
      - ./www:/var/www/html
      - ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./config/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
    networks:
      - internal
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress      
      WORDPRESS_DB_PASSWORD: wordpress

  memcached:
    image: memcached:alpine
    environment:
      - "MEMCACHED_CACHE_SIZE=64"
    restart: unless-stopped
    networks:
      - internal

  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/conf:/etc/mysql/conf.d
    restart: unless-stopped
    command: mysqld --innodb-buffer-pool-size=20M
    networks:
      - internal
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  traefik:
    image: traefik:alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    networks:
      - front
    labels:
      traefik.enable: false
      traefik.docker.network: traefik_front
      traefik.port: 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik/traefik.toml:/traefik.toml
      - acme:/acme
    container_name: traefik

volumes:
  mysql_data:
  acme:

networks:
  internal: 
  front:
    name: traefik_front
    external: true
