version: '2.1'

services:
#### WEB SERVER CONTAINER
   nginx:
     image: nginx:alpine
     ports:
        - "80:80"
     volumes:
        - ./config/nginx:/etc/nginx/conf.d
        - ./logs/nginx:/var/log/nginx
        - ./www:/var/www/html
     command: /bin/sh -c "nginx -g 'daemon off;'"
#    restart: always
     depends_on:
        - wordpress

#### PHP WORDPRESS CONTAINER
   wordpress:
     build: .
#     restart: always
     volumes:
         - ./www:/var/www/html
         - ./config/php/xdebug-development.ini:/usr/local/etc/php/conf.d/xdebug-development.ini
         - ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
         - ./config/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
     ports:
        - "9010:9010"
     depends_on:
        - db
     environment:
       WORDPRESS_DB_HOST: db
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
#### MEMCAHED CONTAINER
   memcached:
    image: memcached:alpine
    mem_limit: 64m

#### DATABASE CONTAINER
   db:
     image: mysql:5.7
     volumes:
       - ./db/data:/var/lib/mysql
       - ./config/mysql:/etc/mysql/conf.d
#     restart: always
#     command: mysqld  --innodb-buffer-pool-size=20M
#    user: "1000:50"
     ports:
        - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress