[global]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.http]

[providers]
  providersThrottleDuration = "2s"
  [providers.docker]
    watch = true
    endpoint = "unix:///var/run/docker.sock"
    swarmModeRefreshSeconds = "15s"
    httpClientTimeout = "0s"

[api]
  insecure = true
  dashboard = true

[log]
  level = "INFO"
